[package]
name = "qperformance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.7"
csv = "1.3.0"
serde = "1.0.203"
lazy_static = "1.4.0"
regex = "1.10.5"